#!/usr/bin/php -q
<?php
require("config");

// Connect to the central MySQL server and exit if it cant
$link = @mysql_connect ($DBHost, $DBUsername, $DBPassword);
if (!$link) { exit; }
mysql_select_db ($DBName, $link);

// Get the settings that apply to the current server
$hostname = exec("hostname -s");
$servers = mysql_query ("SELECT DNS, Mail, HTTP, DB FROM Servers WHERE Name='" . mysql_escape_string($hostname) . "';", $link);
if (@mysql_num_rows($servers) == 0) {
  print "There is no entry for this server.\n";
} else {
  $server = @mysql_fetch_array($servers);

  // Update everything as necessary
  system("./updateusers");
  if ($server['Mail']) { system("./updatemail"); }
  if ($server['DNS']) { system("./updatedns"); }
  if ($server['HTTP']) { system("./updateweb"); }
}

// Clean up
mysql_free_result($servers);
mysql_close($link);
?>
