#!/usr/bin/php -q
<?php
require("config");
require("common");

ini_set("html_errors", 0);

// Connect to the central MySQL server and exit if it cant
$link = @mysql_connect ($DBHost, $DBUsername, $DBPassword);
if (!$link) { 
  print "Unable to connect to the database server.\n";
  exit;
}
mysql_select_db ($DBName, $link);

// Get the settings that apply to the current server
$hostname = exec("hostname -s");
$servers = mysql_query ("SELECT ID, FullName, Address, Live, Updated, DNS, Mail, HTTP, DB, Shell FROM Servers WHERE Name='" . mysql_escape_string($hostname) . "';", $link);
if (mysql_num_rows($servers) == 0) {
  mysql_free_result($servers);
  print "There is no entry for this server.\n";
} else {
  $server = mysql_fetch_array($servers);
  mysql_free_result($servers);
  if ($server['Live']) {
    $localserverid = $server['ID'];
    $localservername = $server['FullName'];
    $localserveraddress = $server['Address'];
    $lastupdated = mysql_to_date($server['Updated']);

    // Update everything as necessary
    include("updateusers");
    if ($server['DNS']) { include("updatedns"); }
    if ($server['Mail']) { include("updatemail"); }
    if ($server['HTTP']) { include("updateweb"); }
    if ($server['DB']) { include("updatedb"); }
    if ($server['List']) { include("updatelist"); }

    #Contributed scripts
    for ($contribid = 0; $contribid < count($Contribs); $contribid++) {
      if (file_exists("update" . $Contribs[$contribid])) { include("update" . $Contribs[$contribid]); }
    }

    $servers = mysql_query ("UPDATE Servers SET Updated=Now() WHERE ID='" . mysql_escape_string($localserverid) . "';", $link);
  }
}

// Clean up
mysql_close($link);
?>
